### ISSUE TITLE
Inverse Kinematics

### ISSUE THREAD

**Issue by iftahnaf** [dvalenciar/robotic_arm_environment#2]
Hey @dvalenciar,

First of all, thanks for sharing this project, I followed your instructions and everything works great.
I created a `.devcontainer` in VSCode, with all the necessary dependencies, and everything is running inside a container, I can contribute it if you are interested.

I want to use your setup for a simple simulation where the controller is moving the tip to a specific position - meaning I want to send `[x, y, z]` point to the controller (where `[x, y, z]` are in `world` coordinate). Is there any inverse kinematics calculation of this robot, which will give me the required joint positions?

**Comment by dvalenciar** [comment]
Hello @iftahnaf 

Very sorry for my late late response. Glad to know you successfully installed and found this work interesting. I am always open to collaboration, and I plan to make this simulation more solid and robust for testing several RL algorithms. Since I created this to be used with AI algorithms, I do not have inverse kinematic or related calculation, even do it may be necessary for future comparations
